int a = 1;
short b = -5;
long c = 400;
byte d = 3;
char e = 'a';
string f = "b";
bool g = true;
double h = 0.3;
float i = 4.5f;
decimal j = 10.8m;
uint k = 6;
ushort l = 20;
ulong m = 95;
sbyte n = 5;

a = 5;
b = 4;
c = -32;
d = 1;
e = 'c';
f = "hi";
g = false;
h = -4.5;
i = 3.2f;
j = 42.1m;
k = 21;
l = 49;
m = 35;
n = 2;

Console.WriteLine(a);
Console.WriteLine(b);
Console.WriteLine(c);
Console.WriteLine(d);
Console.WriteLine(e);
Console.WriteLine(f);
Console.WriteLine(g);
Console.WriteLine(h);
Console.WriteLine(i);
Console.WriteLine(j);
Console.WriteLine(k);
Console.WriteLine(l);
Console.WriteLine(m);
Console.WriteLine(n);