int a = 1;
short b = -5;
long c = 400;
byte d = 3;
char e = 'a';
string f = "b";
bool g = true;
double h = 0.3;
float i = 4.5f;
decimal j = 10.8m;
uint k = 6;
ushort l = 20;
ulong m = 95;
sbyte n = 5;

Console.WriteLine(a);
Console.WriteLine(b);
Console.WriteLine(c);
Console.WriteLine(d);
Console.WriteLine(e);
Console.WriteLine(f);
Console.WriteLine(g);
Console.WriteLine(h);
Console.WriteLine(i);
Console.WriteLine(j);
Console.WriteLine(k);
Console.WriteLine(l);
Console.WriteLine(m);
Console.WriteLine(n);